; ============================================================
; Anaconda XB 360 - Apps
; ============================================================

[AnacondaFileManager]
itemTitle=Anaconda File Manager
itemVersion=1.0
itemAuthor=H3X Anaconda Team
itemDescription=A simple file manager for Xbox 360.
dataurl=https://github.com/H3X-Anaconda-Team/anaconda-xb-360/releases/download/v1.0/AnacondaFileManager.7z
path=/Apps/AnacondaFileManager/
reload=True

[AnacondaFTP]
itemTitle=Anaconda FTP
itemVersion=1.0
itemAuthor=H3X Anaconda Team
itemDescription=Quick FTP server for transferring files.
dataurl=https://github.com/H3X-Anaconda-Team/anaconda-xb-360/releases/download/v1.0/AnacondaFTP.7z
path=/Apps/AnacondaFTP/
reload=True
