; ============================================================
; Anaconda XB 360 - Emulators
; ============================================================

[ExampleEmulator]
itemTitle=Example Emulator
itemVersion=1.0
itemAuthor=H3X Anaconda Team
itemDescription=Example emulator entry for Anaconda XB 360.
dataurl=https://github.com/H3X-Anaconda-Team/anaconda-xb-360/releases/download/v1.0/ExampleEmulator.7z
path=/Emulators/ExampleEmulator/
reload=True
