; ============================================================
; Anaconda XB 360 - Games
; ============================================================

[ExampleHomebrewGame]
itemTitle=Example Homebrew Game
itemVersion=1.0
itemAuthor=H3X Anaconda Team
itemDescription=A small homebrew game.
dataurl=https://github.com/H3X-Anaconda-Team/anaconda-xb-360/releases/download/v1.0/ExampleHomebrewGame.zip
path=/Games/ExampleHomebrewGame/
reload=True
